### PR TITLE
Building features

### PR DESCRIPTION
**Pull request by tedsmoore**
Moving the BuildFeatures class to the build_features module and adding some structure. Now it actually creates some potentially useful features like `Adj Close - SMA` and `Adj Close Slope`. 

Also, I've added the first "Label", which is simply a 1 if stock will go up the following day. This is called in the `onFinish()` method because we need "future" data to apply a label to a given row.

### CODE REVIEW

**Review by cicorias — APPROVED** [review]
LGTM

**Comment by cicorias** [comment]
@tedsmoore wasn't sure if you wanted to merge, but I did.

There is a Draft PR state that you can use -- and it won't prompt for review and merge.

BTW, you can approve your OWN i believe and merge too, even override.  I think.  If not there's a setting for that.

**Comment by tedsmoore** [comment]
Ahh ok cool - I'll look for the draft setting next time. I just wanted to share the direction I was going, even if it wasn't a complete thought yet. No biggie.

To some extent I kind of like the required reviews, it keeps us a bit more rigid with PRs and prompts discussion about code. But it could be overkill.

I figure tomorrow we can chat about some conventions, both in the workflow and the actual code design, now that we've had a couple days to explore and try stuff out.

**Comment by cicorias** [comment]
I’m fine approving too just don’t want to be a blocker

**Pull request merged**
