### PR TITLE
Graphing

### PR DESCRIPTION
**Pull request by dapolloxp**
Adding basic graphing. Will convert to class later and add the ability to toggle the type of graphing abilities.

### CODE REVIEW

**Comment by cicorias** [comment]
Could you add to .gitignore in the root .DS_store and update the branch?

**Review by cicorias — CHANGES_REQUESTED** [review]
Modify .gitignore to eliminate.DS_Store

**Comment by dapolloxp** [comment]
Removed .DS_store

**Comment by cicorias** [comment]
i added seaborn to poetry dependencies and removed xtra ds_store. -- pull to refresh..  but otherwise can merge. @tedsmoore @dapolloxp

**Review by cicorias — APPROVED** [review]

**Pull request merged**
